#!/bin/sh

NODE_BIN=${NODE_BINARY:-morphnode}
NODE_HOME=${NODE_HOME:-/db}
JWT_PATH=${JWT_SECRET_PATH:-/jwt-secret.txt}

# L2 connection defaults (localhost for binary mode; Docker overrides via environment section)
export MORPH_NODE_L2_ETH_RPC=${MORPH_NODE_L2_ETH_RPC:-http://localhost:8545}
export MORPH_NODE_L2_ENGINE_RPC=${MORPH_NODE_L2_ENGINE_RPC:-http://localhost:8551}
export MORPH_NODE_L2_ENGINE_AUTH=${MORPH_NODE_L2_ENGINE_AUTH:-${JWT_PATH}}

# Map .env variables to MORPH_NODE_* for binary mode (Docker sets these directly)
export MORPH_NODE_L1_ETH_RPC=${MORPH_NODE_L1_ETH_RPC:-${L1_ETH_RPC:-}}
export MORPH_NODE_ROLLUP_ADDRESS=${MORPH_NODE_ROLLUP_ADDRESS:-${ROLLUP_CONTRACT:-}}

# Validator-specific mappings
export MORPH_NODE_L1_ETH_BEACON_RPC=${MORPH_NODE_L1_ETH_BEACON_RPC:-${L1_BEACON_CHAIN_RPC:-}}
export MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS:-${L1MESSAGEQUEUE_CONTRACT:-}}
export MORPH_NODE_DERIVATION_START_HEIGHT=${MORPH_NODE_DERIVATION_START_HEIGHT:-${DERIVATION_START_HEIGHT:-}}
export MORPH_NODE_DERIVATION_BASE_HEIGHT=${MORPH_NODE_DERIVATION_BASE_HEIGHT:-${L2_BASE_HEIGHT:-}}
export MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-${L1_MSG_START_HEIGHT:-}}
export MORPH_NODE_L1_CHAIN_ID=${MORPH_NODE_L1_CHAIN_ID:-${L1_CHAIN_ID:-}}

COMMAND="${NODE_BIN} \
--home ${NODE_HOME} \
--log.filename ${NODE_HOME}/node.log \
${NODE_EXTRA_FLAGS:-}"

eval $COMMAND
